name       : gnome-twitch
version    : 0.4.0
release    : 7
source     :
    - https://github.com/vinszent/gnome-twitch/archive/v0.4.0.tar.gz : 641df662ba8623034ceb21f1efb0345d052d1a0deddb9a3d926d36b4990eeefd
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME Twitch app for watching Twitch on your GNU/Linux desktop.
description: |
    GNOME Twitch app for watching Twitch on your GNU/Linux desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mpv)
    - pkgconfig(webkit2gtk-4.0)
    - meson
    - ninja
setup      : |
    export LANG=en_US.utf8
    export LC_ALL=en_US.utf8
    %meson_configure --prefix /usr --libdir lib64 \
             --buildtype release \
             -Dbuild-player-backends=gstreamer-cairo,gstreamer-opengl,gstreamer-clutter,mpv-opengl \
             -Db_lundef=false \
             -Ddo-post-install=false
build      : |
    export LANG=en_US.utf8
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LANG=en_US.utf8
    export LC_ALL=en_US.utf8
    %meson_install
