name       : gnome-twitch
version    : 0.3.1
release    : 6
source     :
    - https://github.com/vinszent/gnome-twitch/archive/v0.3.1.tar.gz : 079fd7b26646512ba881d924614dc8f3a645d8bb3c2d1576f861ca47e1190b74
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME Twitch app for watching Twitch on your GNU/Linux desktop.
description: |
    GNOME Twitch app for watching Twitch on your GNU/Linux desktop.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mpv)
    - pkgconfig(webkit2gtk-4.0)
    - meson
    - ninja
setup      : |
    mkdir build && cd build
    %meson_configure --prefix /usr --libdir lib64 \
             --buildtype release \
             -Dwith-player-gstreamer-clutter=true \
             -Dwith-player-gstreamer-cairo=true \
             -Dwith-player-gstreamer-opengl=true \
             -Dwith-player-mpv-opengl=true \
             -Db_lundef=false \
             -Ddo-post-install=false ..
build      : |
    cd build
    %meson_build
install    : |
    cd build
    %meson_install
